package Vista;

import javax.swing.table.DefaultTableModel;
import Modelo.GestorPaciente;
import Modelo.Paciente;
import Modelo.Cita;
import Modelo.Medico;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.LinkedList;

import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;

public class ConsPacienteInternalFrame extends javax.swing.JInternalFrame {

    private final GestorPaciente gestorPaciente;
    private final DefaultTableModel tablaP, tablaC, tablaM;
    private JTabbedPane tabbedPane;
    private JTable tablePacientes, tableCitas, tableMedicos;
            
public ConsPacienteInternalFrame(){
    initComponents();
    this.gestorPaciente = new GestorPaciente();

    String titulosTablaP[] = {"Identificatión", "Nombres", "Apellidos", "Fecha Nacimiento", "Genero"};
    tablaP = new DefaultTableModel(null, titulosTablaP);
    tablePacientes = new JTable(tablaP);

    String titulosTablaC[] = {"Fecha", "Hora", "Paciente", "Medico"};
    tablaC = new DefaultTableModel(null, titulosTablaC);
    tableCitas = new JTable(tablaC);
    
    String titulosTablaM[] = {"Nombre", "Especialidad"};
    tablaM = new DefaultTableModel(null, titulosTablaM);
    tableMedicos = new JTable(tablaM);

    tabbedPane = new JTabbedPane();
    tabbedPane.addTab("Pacientes", new JScrollPane(tablePacientes));
    tabbedPane.addTab("Citas", new JScrollPane(tableCitas));
    tabbedPane.addTab("Médicos", new JScrollPane(tableMedicos));
    getContentPane().add(tabbedPane);

    //Cargar los datos iniciales en las tablas
    buscarPacientes();
    buscarCitas();
    buscarMedicos();
    }

    private void buscarPacientes() {
        String parametro = "";
        if (rdb_identificacion.isSelected()) {
            parametro = "pacIdentificacion";
        } else if (rdb_nombres.isSelected()) {
            parametro = "pacNombres";
        } else if (rdb_apellidos.isSelected()) {
            parametro = "pacApellidos";
        } else if (rdb_genero.isSelected()) {
            parametro = "pacGenero";
        }

        // Verificar si se ha seleccionado un parámetro de búsqueda
        if (!parametro.isEmpty()) {
            String valor = jTextField1.getText();
            LinkedList<Paciente> pacientes = gestorPaciente.getPacientesByParametro(parametro, valor);
            tablaP.setRowCount(0);
            for (Paciente paciente : pacientes) {
                Object[] fila = {
                    paciente.getIdentificacion(),
                    paciente.getNombres(),
                    paciente.getApellidos(),
                    paciente.getFechaNacimiento(),
                    paciente.getGenero()
                };
                tablaP.addRow(fila);
            }
        } else {
            // Mostrar un mensaje de error si no se ha seleccionado ningún parámetro
            JOptionPane.showMessageDialog(this, "Debe seleccionar un parámetro de búsqueda", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

        private void buscarCitas() {
            LinkedList<Cita> citas = gestorPaciente.obtenerCitas();
            tablaC.setRowCount(0);
            for (Cita cita : citas) {
                Object[] fila = {cita.getFecha(), cita.getHora(), cita.getPaciente(), cita.getMedico()};
                tablaC.addRow(fila);
            }
        }

       private void buscarMedicos() {
        LinkedList<Medico> medicos = gestorPaciente.obtenerMedicos();
        tablaM.setRowCount(0);
        for (Medico medico : medicos) {
            Object[] fila = {medico.getNombre(), medico.getEspecialidad()};
            tablaM.addRow(fila);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdb_identificacion = new javax.swing.JRadioButton();
        rdb_nombres = new javax.swing.JRadioButton();
        rdb_apellidos = new javax.swing.JRadioButton();
        rdb_genero = new javax.swing.JRadioButton();
        txt_valor = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btn_aceptar = new javax.swing.JButton();
        btn_consultarCitas = new javax.swing.JButton(); 
        btn_consultarMedicos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_datos = new javax.swing.JTable();

        btn_aceptar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                buscarPacientes();
            }
        });

        btn_consultarCitas.setText("Consultar Citas"); // Texto del nuevo botón
        btn_consultarCitas.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                buscarCitas();
            }
        });

        btn_consultarMedicos.setText("Consultar Médicos"); // Texto del nuevo botón
        btn_consultarMedicos.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                buscarMedicos();
            }
        });

        rdb_identificacion.setText("Identificación");
        rdb_identificacion.setName(""); // NOI18N

        rdb_nombres.setText("Nombres");

        rdb_apellidos.setText("Apellidos");

        rdb_genero.setText("Genero");

        txt_valor.setText("Valor a buscar:");
        txt_valor.setToolTipText("Valor a buscar:");
        txt_valor.setName("ValorTxt"); // NOI18N

        jTextField1.setName("ValorTxt"); // NOI18N

        btn_aceptar.setText("Aceptar");
        btn_aceptar.setName("AceptarBtn"); // NOI18N

        Tbl_datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tbl_datos.setName("ResultadosTbl"); // NOI18N
        jScrollPane1.setViewportView(Tbl_datos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdb_identificacion)
                        .addGap(18, 18, 18)
                        .addComponent(rdb_nombres)
                        .addGap(18, 18, 18)
                        .addComponent(rdb_apellidos)
                        .addGap(18, 18, 18)
                        .addComponent(rdb_genero))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_valor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_aceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_consultarCitas) // Añadir botón de consultar citas
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_consultarMedicos)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdb_identificacion)
                    .addComponent(rdb_nombres)
                    .addComponent(rdb_apellidos)
                    .addComponent(rdb_genero))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_valor)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_aceptar)
                    .addComponent(btn_consultarCitas) // Añadir botón de consultar citas
                    .addComponent(btn_consultarMedicos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable Tbl_datos;
    public javax.swing.JButton btn_aceptar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JRadioButton rdb_apellidos;
    public javax.swing.JRadioButton rdb_genero;
    public javax.swing.JRadioButton rdb_identificacion;
    public javax.swing.JRadioButton rdb_nombres;
    public javax.swing.JLabel txt_valor;
    public javax.swing.JButton btn_consultarCitas; 
    public javax.swing.JButton btn_consultarMedicos;
    // End of variables declaration//GEN-END:variables

   
        }
    



